export const STRINGS = {
  fa: {
    save: 'ذخیره',
    gallery: 'گالری',
    donate: 'حمایت مالی',
    settings: 'تنظیمات',
    placeholder: 'اینجا بنویسید…',
    clear: 'پاک کردن',
    tabFont: 'فونت',
    tabStyle: 'استایل',
    tabBox: 'جعبه متن',
    tabColor: 'رنگ متن',
    tabBg: 'پس‌زمینه',
    tabLayout: 'چیدمان',
    yourFont: 'فونت خودت',
    bold: 'بولد',
    italic: 'ایتالیک',
    underline: 'زیرخط',
    shadow: 'سایه',
    stroke: 'دورخط',
    myImage: 'عکس من',
    uploadImage: 'آپلود عکس',
    size: 'اندازه',
    letterSpacing: 'فاصله حروف',
    lineHeight: 'فاصله خطوط',
    strokeWidth: 'ضخامت دورخط',
    opacity: 'شفافیت متن',
    margin: 'حاشیه',
    align_right: 'راست',
    align_center: 'وسط',
    align_left: 'چپ',
    saveToDevice: 'ذخیره در گالری دستگاه (PNG)',
    copyImageBtn: 'کپی عکس در کلیپ‌بورد',
    copyTextBtn: 'کپی متن',
    saveToAppGallery: 'ذخیره در گالری برنامه',
    myGallery: 'گالری من',
    emptyGallery: 'چیزی ذخیره نشده. یک متن بساز و ذخیره کن.',
    donateText: 'درآمد این بخش صرف خرید لایسنس فونت‌های جدید و اضافه‌کردن‌شون به FontWoW می‌شه.',
    payViaZibal: 'پرداخت از طریق زیبال',
    donateNotSet: 'لینک درگاه هنوز تنظیم نشده.',
    themeColor: 'رنگ تم برنامه',
    language: 'زبان',
    contact: 'ارتباط با ما',
    version: 'نسخه',
    resetSettings: 'بازگردانی تنظیمات',
    openSource: 'متن‌باز روی گیت‌هاب',
    fontAdded: 'فونت اضافه شد',
    fontError: 'خطا در بارگذاری فونت',
    bgAdded: 'پس‌زمینه اضافه شد',
    bgError: 'خطا در بارگذاری عکس',
    imageSaved: 'عکس ذخیره شد',
    imageError: 'خطا در ساخت عکس',
    imageCopied: 'عکس در کلیپ‌بورد کپی شد',
    imageCopyFallback: 'کپی عکس پشتیبانی نشد؛ متن کپی شد',
    copyFailed: 'کپی ناموفق بود',
    textCopied: 'متن کپی شد',
    writeFirst: 'اول یک متن بنویس',
    savedToGallery: 'در گالری ذخیره شد',
  },
  en: {
    save: 'Save',
    gallery: 'Gallery',
    donate: 'Support',
    settings: 'Settings',
    placeholder: 'Type here…',
    clear: 'Clear',
    tabFont: 'Font',
    tabStyle: 'Style',
    tabBox: 'Text Box',
    tabColor: 'Color',
    tabBg: 'Background',
    tabLayout: 'Layout',
    yourFont: 'Your Font',
    bold: 'Bold',
    italic: 'Italic',
    underline: 'Underline',
    shadow: 'Shadow',
    stroke: 'Outline',
    myImage: 'My Image',
    uploadImage: 'Upload Image',
    size: 'Size',
    letterSpacing: 'Letter Spacing',
    lineHeight: 'Line Height',
    strokeWidth: 'Outline Width',
    opacity: 'Opacity',
    margin: 'Margin',
    align_right: 'Right',
    align_center: 'Center',
    align_left: 'Left',
    saveToDevice: 'Save to device gallery (PNG)',
    copyImageBtn: 'Copy image to clipboard',
    copyTextBtn: 'Copy text',
    saveToAppGallery: 'Save to app gallery',
    myGallery: 'My Gallery',
    emptyGallery: 'Nothing saved yet. Create something and save it.',
    donateText: 'Proceeds go toward licensing new fonts for FontWoW.',
    payViaZibal: 'Pay via Zibal',
    donateNotSet: 'Payment link is not set yet.',
    themeColor: 'App Theme Color',
    language: 'Language',
    contact: 'Contact Us',
    version: 'Version',
    resetSettings: 'Reset Settings',
    openSource: 'Open source on GitHub',
    fontAdded: 'Font added',
    fontError: 'Failed to load font',
    bgAdded: 'Background added',
    bgError: 'Failed to load image',
    imageSaved: 'Image saved',
    imageError: 'Failed to create image',
    imageCopied: 'Image copied to clipboard',
    imageCopyFallback: 'Image copy not supported; text copied instead',
    copyFailed: 'Copy failed',
    textCopied: 'Text copied',
    writeFirst: 'Write some text first',
    savedToGallery: 'Saved to gallery',
  },
}
