export const STRINGS = {
  fa: {
    save: 'ذخیره',
    gallery: 'گالری',
    donate: 'حمایت مالی',
    settings: 'تنظیمات',
    undo: 'برگردان',
    redo: 'انجام دوباره',
    placeholder: 'اینجا بنویسید…',
    clear: 'پاک کردن',
    tabFont: 'فونت',
    tabStyle: 'استایل',
    tabBox: 'جعبه متن',
    tabColor: 'رنگ متن',
    tabBg: 'پس‌زمینه',
    tabLayout: 'چیدمان',
    tabTemplates: 'قالب‌ها',
    yourFont: 'فونت خودت',
    effect: 'افکت متن',
    brightness: 'روشنایی',
    contrast: 'کنتراست',
    blur: 'بلور',
    grayscale: 'سیاه‌وسفید',
    aspectRatio: 'نسبت ابعاد',
    addLayer: 'افزودن متن جدید',
    addSticker: 'افزودن استیکر/عکس',
    addLabel: 'افزودن لیبل',
    tabAssets: 'دارایی‌ها',
    labelAssets: 'لیبل‌های آماده',
    labelAssetsHint: 'یک لیبل انتخاب کن؛ متن و رنگش بعداً قابل تغییر است.',
    labelPriceTag: 'تگ قیمت',
    labelStarburst: 'نشان تخفیف',
    labelRibbon: 'روبان',
    labelPill: 'کپسولی',
    labelTicket: 'بلیط',
    labelCircle: 'دایره',
    labelBanner: 'بنر',
    labelSpeech: 'حباب گفتگو',
    labelFlag: 'پرچم',
    newLabelText: 'تخفیف ویژه',
    editLabelText: 'متن لیبل را ویرایش کن',
    editSelectedLabel: 'ویرایش لیبل انتخاب‌شده',
    labelColor: 'رنگ لیبل',
    labelTextColor: 'رنگ متن',
    labelFont: 'فونت لیبل',
    labelTextHorizontal: 'جابه‌جایی متن افقی',
    labelTextVertical: 'جابه‌جایی متن عمودی',
    editLayerText: 'متن این لایه را ویرایش کن',
    deleteLayer: 'حذف لایه',
    newLayerText: 'متن جدید',
    bold: 'بولد',
    italic: 'ایتالیک',
    underline: 'زیرخط',
    shadow: 'سایه',
    stroke: 'دورخط',
    myImage: 'عکس من',
    uploadImage: 'آپلود عکس',
    size: 'اندازه',
    letterSpacing: 'فاصله حروف',
    lineHeight: 'فاصله خطوط',
    strokeWidth: 'ضخامت دورخط',
    opacity: 'شفافیت متن',
    margin: 'حاشیه',
    align_right: 'راست',
    align_center: 'وسط',
    align_left: 'چپ',
    saveToDevice: 'ذخیره در گالری دستگاه (PNG)',
    copyImageBtn: 'کپی عکس در کلیپ‌بورد',
    copyTextBtn: 'کپی متن',
    saveToAppGallery: 'ذخیره در گالری برنامه',
    myGallery: 'گالری من',
    emptyGallery: 'چیزی ذخیره نشده. یک متن بساز و ذخیره کن.',
    donateText:
      'تمام مبالغی که حمایت مالی می‌شن صرف خرید فونت‌های جدید با لایسنس می‌شه تا رایگان و در دسترس همه توی FontWoW قرار بگیرن.',
    payViaZibal: 'پرداخت تومانی (درامت)',
    payViaCrypto: 'پرداخت با کریپتو',
    donateNotSet: 'لینک درگاه هنوز تنظیم نشده.',
    suggestFontLabel: 'دوست داری چه فونتی اضافه بشه؟',
    suggestFontPlaceholder: 'اسم فونت مورد نظرت رو بنویس…',
    sendSuggestion: 'ارسال پیشنهاد فونت',
    themeColor: 'رنگ تم برنامه',
    language: 'زبان',
    contact: 'ارتباط با ما',
    version: 'نسخه',
    whatsNew: 'آخرین تغییرات',
    updateAvailable: 'نسخه‌ی جدید در دسترسه',
    updateDownload: 'دانلود آپدیت',
    shareKitLink: 'پک رسانه‌ای و اشتراک‌گذاری',
    shareKitTitle: 'پک رسانه‌ای و اشتراک‌گذاری FontWoW',
    shareKitDesc: 'با فونت‌واو (FontWoW) متن‌های استوری خیره‌کننده بساز و با دوستان و دیگر طراحان به اشتراک بگذار!',
    downloadPromo: 'دانلود تصویر با کیفیت بالا',
    promoStoryTab: 'استوری اینستاگرام (۹:۱۶)',
    promoPostTab: 'پست اینستاگرام (۱:۱)',
    copyPromoText: 'کپی متن معرفی برنامه',
    promoCopiedToast: 'متن معرفی کپی شد!',
    projectLink: 'لینک پروژه',
    featuresTitle: 'امکانات و قابلیت‌های کلیدی',
    downloadAppTitle: 'دانلود نرم‌افزار از مارکت‌های مختلف',
    downloadApk: 'دانلود مستقیم APK (اندروید)',
    downloadBazaar: 'دریافت از کافه بازار',
    downloadMyket: 'دریافت از مایکت',
    downloadWebApp: 'اجرای نسخه تحت وب (PWA)',
    resetSettings: 'بازگردانی تنظیمات',
    openSource: 'متن‌باز روی گیت‌هاب',
    fontAdded: 'فونت اضافه شد',
    fontError: 'خطا در بارگذاری فونت',
    bgAdded: 'پس‌زمینه اضافه شد',
    bgError: 'خطا در بارگذاری عکس',
    imageSaved: 'عکس ذخیره شد',
    imageError: 'خطا در ساخت عکس',
    imageCopied: 'عکس در کلیپ‌بورد کپی شد',
    imageShared: 'کلیپ‌بورد در دسترس نبود؛ عکس برای اشتراک‌گذاری باز شد',
    imageCopyFallback: 'کپی عکس پشتیبانی نشد؛ متن کپی شد',
    copyFailed: 'کپی ناموفق بود',
    textCopied: 'متن کپی شد',
    writeFirst: 'اول یک متن بنویس',
    savedToGallery: 'در گالری ذخیره شد',
    newStyle: 'استایل جدید',
    styleStudio: 'استودیوی استایل',
    styleStudioHint:
      'فونت، رنگ، جعبه، پس‌زمینه و افکتی که الان روی صفحه انتخاب کردی، به‌عنوان یک استایل ذخیره می‌شه.',
    styleNameLabel: 'اسم استایل',
    styleNamePlaceholder: 'مثلاً: عصر جمعه',
    saveStyleToApp: 'ذخیره در برنامه',
    copyStyleJSON: 'کپی JSON برای افزودن دائمی',
    styleSaved: 'استایل ذخیره شد',
    styleJSONCopied: 'JSON استایل کپی شد؛ توی src/templates.json بچسبونش',
    nameFirst: 'اول یک اسم برای استایل بنویس',
    deleteStyle: 'حذف استایل',
    styleStudioJsonHint:
      'برای اضافه کردن دائمی این استایل به پروژه، این JSON رو کپی کن و به آرایه‌ی داخل src/templates.json اضافه کن.',
    fontLicenses: 'لایسنس فونت‌ها',
    fontLicensesText:
      'تمام فونت‌های موجود در FontWoW از Google Fonts هستن و تحت لایسنس‌های متن‌باز (بیشتر SIL Open Font License، Roboto تحت Apache License 2.0) در اختیار طراح‌هاشون منتشر شدن. حق مالکیت هر فونت متعلق به طراح اصلی‌شه.',
    copyCss: 'کپی CSS',
    downloadCss: 'دانلود CSS',
    copyHtml: 'کپی HTML',
    preview: 'پیشنمایش',
    htmlElement: 'عنصر HTML',
    cssCopied: 'CSS کپی شد',
    htmlCopied: 'HTML کپی شد',
    searchGoogleFonts: 'جستجوی فونت‌های گوگل...',
    addGoogleFont: 'جستجو و افزودن فونت گوگل',
    searchFontsPlaceholder: 'نام فونت را بنویسید (مثلا: Estedad, Inter...)',
    noFontsFound: 'فونتی پیدا نشد',
    alreadyAdded: 'این فونت قبلاً اضافه شده است',
    loadingFont: 'درحال بارگذاری فونت...',
  },
  en: {
    save: 'Save',
    gallery: 'Gallery',
    donate: 'Support',
    settings: 'Settings',
    undo: 'Undo',
    redo: 'Redo',
    placeholder: 'Type here…',
    clear: 'Clear',
    tabFont: 'Font',
    tabStyle: 'Style',
    tabBox: 'Text Box',
    tabColor: 'Color',
    tabBg: 'Background',
    tabLayout: 'Layout',
    tabTemplates: 'Templates',
    yourFont: 'Your Font',
    effect: 'Text Effect',
    brightness: 'Brightness',
    contrast: 'Contrast',
    blur: 'Blur',
    grayscale: 'Grayscale',
    aspectRatio: 'Aspect Ratio',
    addLayer: 'Add text layer',
    addLabel: 'Add label',
    tabAssets: 'Assets',
    labelAssets: 'Ready-made labels',
    labelAssetsHint: 'Pick a label, then customize its text and colors.',
    labelPriceTag: 'Price tag',
    labelStarburst: 'Sale badge',
    labelRibbon: 'Ribbon',
    labelPill: 'Pill',
    labelTicket: 'Ticket',
    labelCircle: 'Circle',
    labelBanner: 'Banner',
    labelSpeech: 'Speech bubble',
    labelFlag: 'Flag',
    newLabelText: 'Special offer',
    editLabelText: 'Edit label text',
    editSelectedLabel: 'Edit selected label',
    labelColor: 'Label color',
    labelTextColor: 'Text color',
    labelFont: 'Label font',
    labelTextHorizontal: 'Text horizontal position',
    labelTextVertical: 'Text vertical position',
    editLayerText: "Edit this layer's text",
    deleteLayer: 'Delete layer',
    newLayerText: 'New text',
    bold: 'Bold',
    italic: 'Italic',
    underline: 'Underline',
    shadow: 'Shadow',
    stroke: 'Outline',
    myImage: 'My Image',
    uploadImage: 'Upload Image',
    size: 'Size',
    letterSpacing: 'Letter Spacing',
    lineHeight: 'Line Height',
    strokeWidth: 'Outline Width',
    opacity: 'Opacity',
    margin: 'Margin',
    align_right: 'Right',
    align_center: 'Center',
    align_left: 'Left',
    saveToDevice: 'Save to device gallery (PNG)',
    copyImageBtn: 'Copy image to clipboard',
    copyTextBtn: 'Copy text',
    saveToAppGallery: 'Save to app gallery',
    myGallery: 'My Gallery',
    emptyGallery: 'Nothing saved yet. Create something and save it.',
    donateText:
      'Every donation goes toward buying licensed fonts, added to FontWoW for free and available to everyone.',
    payViaZibal: 'Pay via Daramet (Toman)',
    payViaCrypto: 'Pay with crypto',
    donateNotSet: 'Payment link is not set yet.',
    suggestFontLabel: 'Which font would you like added?',
    suggestFontPlaceholder: 'Type the font name…',
    sendSuggestion: 'Send font suggestion',
    themeColor: 'App Theme Color',
    language: 'Language',
    contact: 'Contact Us',
    version: 'Version',
    whatsNew: "What's New",
    updateAvailable: 'A new version is available',
    updateDownload: 'Download update',
    shareKitLink: 'Media Kit & Sharing',
    shareKitTitle: 'FontWoW Media Kit & Sharing',
    shareKitDesc: 'Create stunning story texts with FontWoW and share them with your friends and other designers!',
    downloadPromo: 'Download High-Quality Image',
    promoStoryTab: 'Instagram Story (9:16)',
    promoPostTab: 'Instagram Post (1:1)',
    copyPromoText: 'Copy Share Text',
    promoCopiedToast: 'Share text copied to clipboard!',
    projectLink: 'Project Link',
    featuresTitle: 'Key Features & Options',
    downloadAppTitle: 'Download App on Various Sites',
    downloadApk: 'Direct APK Download (Android)',
    downloadBazaar: 'Get on Cafe Bazaar',
    downloadMyket: 'Get on Myket',
    downloadWebApp: 'Open Web App (PWA)',
    resetSettings: 'Reset Settings',
    openSource: 'Open source on GitHub',
    fontAdded: 'Font added',
    fontError: 'Failed to load font',
    bgAdded: 'Background added',
    bgError: 'Failed to load image',
    imageSaved: 'Image saved',
    imageError: 'Failed to create image',
    imageCopied: 'Image copied to clipboard',
    imageShared: 'Clipboard unavailable; opened the share sheet instead',
    imageCopyFallback: 'Image copy not supported; text copied instead',
    copyFailed: 'Copy failed',
    textCopied: 'Text copied',
    writeFirst: 'Write some text first',
    savedToGallery: 'Saved to gallery',
    newStyle: 'New Style',
    styleStudio: 'Style Studio',
    styleStudioHint:
      'The font, color, box, background, and effect currently selected on the canvas will be saved as one style.',
    styleNameLabel: 'Style name',
    styleNamePlaceholder: 'e.g. Friday Evening',
    saveStyleToApp: 'Save in app',
    copyStyleJSON: 'Copy JSON to add permanently',
    styleSaved: 'Style saved',
    styleJSONCopied: 'Style JSON copied; paste it into src/templates.json',
    nameFirst: 'Give your style a name first',
    deleteStyle: 'Delete style',
    styleStudioJsonHint:
      'To add this style to the project permanently, copy this JSON and add it to the array in src/templates.json.',
    fontLicenses: 'Font Licenses',
    fontLicensesText:
      'Every font in FontWoW is served by Google Fonts under open licenses (mostly the SIL Open Font License; Roboto under Apache License 2.0), published by their original designers. Copyright for each font belongs to its designer.',
    copyCss: 'Copy CSS',
    downloadCss: 'Download CSS',
    copyHtml: 'Copy HTML',
    preview: 'Preview',
    htmlElement: 'HTML Element',
    cssCopied: 'CSS copied!',
    htmlCopied: 'HTML copied!',
    searchGoogleFonts: 'Search Google Fonts...',
    addGoogleFont: 'Search & Add Google Font',
    searchFontsPlaceholder: 'Type font name (e.g. Estedad, Inter...)',
    noFontsFound: 'No fonts found',
    alreadyAdded: 'This font is already added',
    loadingFont: 'Loading font...',
  },
}
